-define(GRAPH_URL, "https://graph.facebook.com").
-define(AUTH_URL,  "https://graph.facebook.com/oauth/authorize").
-define(TOKEN_URL, "https://graph.facebook.com/oauth/access_token").
-define(DEBUG_URL, "https://graph.facebook.com/debug_token").